[tool.poetry]
name = "meows-finance-bot"
version = "0.1.0"
description = "Telegram finance bot"
authors = ["Dmitry Manuev"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
python-telegram-bot = {version = "21.10", extras = ["job-queue"]}
python-dotenv = "1.0.1"
oauth2client = "4.1.3"
httplib2 = "0.22.0"
google-api-python-client = "2.140.0"
openai = ">=1.0,<2.0"

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"
